### ISSUE TITLE
DFD Comments Feb 16

### ISSUE THREAD

**Issue by germonprez** [thekatelarsen/ISQA3420#11]
Here are a few comments

1) In this area, it is not clear how new policies are created or how existing policies are edited. 
<img width="192" alt="screen shot 2017-02-16 at 6 43 57 pm" src="https://cloud.githubusercontent.com/assets/656208/23050572/0866b892-f478-11e6-9fbd-3e210bed4384.png">

2) In this area, you should create two different processes. The first process is the one that you have. The second process is the one that the Manager (and Developer) uses to get information out of the database. The second process could be called something like: Query DB for L&V information

<img width="192" alt="screen shot 2017-02-16 at 6 45 30 pm" src="https://cloud.githubusercontent.com/assets/656208/23050608/42ebb1f2-f478-11e6-9327-70db6dd7b7b9.png">

**Comment by thekatelarsen** [comment]
![dfd 7](https://cloud.githubusercontent.com/assets/25017728/23223406/9fc181b4-f8f0-11e6-9819-4945dd1c88a6.PNG)
